# Generated by Django 3.2.3 on 2021-05-13 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pics', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pics',
            options={'verbose_name': 'picture', 'verbose_name_plural': 'pictures'},
        ),
        migrations.AddField(
            model_name='pics',
            name='img',
            field=models.ImageField(default=1, upload_to='images/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pics',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
